# Model
model_name_or_path: /data/bailong/models/opt-350m
num_predictions: 30
remove_duplicates: false

# Fine-tune
stage: sft
finetuning_type: lora
lora_target: q_proj,v_proj

# Dataset setting
dataset_dir: /data/bailong/data/tkg_data
prepare_dir: /data/bailong/data/llm4tkg/prepare
train_dataset: ICEWS14,ICEWS18
valid_dataset: ICEWS14
test_dataset: ICEWS14
history_type: entity
history_direction: uni
history_length: 30
anonymize_strategy: session
anonymize_prefix: false
time_process_strategy: query
vague_time: false
prompt_construct_strategy: inline

# Train
output_dir: /data/bailong/data/llm4tkg/outputs/opt-350m-icews14-icews18-stage1-sft
overwrite_output_dir: true
do_train: true
do_eval: false
do_predict: false
per_device_train_batch_size: 1
gradient_accumulation_steps: 1  # should adapt to parallel training
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true
logging_steps: 10
save_steps: 500
plot_loss: true
