### model
model_name_or_path: /home/gomall/models/llama3_8b

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: prepare
dataset: ICEWS14-train-stage2-hop-50-global-session-ent-rel-1024
template: empty
cutoff_len: 1024
preprocessing_num_workers: 8

### output
output_dir: outputs/fs-icews14-from-pt
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
