### model
model_name_or_path: models/GL-GDELT-WIKI-130k-RID
adapter_name_or_path: outputs/LR-ICEWS14-05-FID
infer_backend: huggingface

### method
stage: sft
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: processed
dataset: ICEWS14
template: empty
cutoff_len: 1024
preprocessing_num_workers: 8

### Process options
history_strategy: hop
history_length: 50
map_strategy: FID
time: session
entity: true
relation: true
