# Paths
dataset_dir: data
dataset: ICEWS14-05,ICEWS14-20,ICEWS14-50
prepare_dir: processed
partition: train

# Process options
history_strategy: hop
history_length: 50
map_strategy: RID
time: session
entity: true
relation: true
