### model
model_name_or_path: meta-llama/Meta-Llama-3-8B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data
dataset: ICEWS14
prepare_dir: prepare
template: default
cutoff_len: 1024
history_strategy: rule_plus
history_length: 30
map_strategy: global
time: global
entity: true
relation: true

### output
output_dir: models/icews14
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
