# Paths
dataset_dir: data
dataset: ICEWS14,ICEWS18,YAGO
prepare_dir: processed
partition: all

# Process options
history_strategy: hop
history_length: 50
map_strategy: GID
time: session
entity: true
relation: true
