# Paths
dataset_dir: data
dataset: ICEWS14
prepare_dir: processed
partition: all

# Process options
history_strategy: hop
history_length: 50
map_strategy: GID
time: session
entity: false
relation: true
