### model
model_name_or_path: models/llama3_8b

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: processed
dataset: GDELT-train-hop-50-RID-session-100000,WIKI-train-hop-50-RID-session-30000
template: empty
cutoff_len: 1024
preprocessing_num_workers: 8

### output
output_dir: outputs/GL-GDELT-WIKI-130k-RID
logging_steps: 10
save_steps: 20000
plot_loss: true
overwrite_output_dir: true

### train, default to use 4 cores
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
