# Model
model_name_or_path: /home/bingxing2/home/scx6592/zuoyuxin/LLM/LLaMA3-8B
adapter_name_or_path: /home/bingxing2/home/scx6592/bailong/data/llm4tkg/saves/llama3-icews14-stage1-sft
template: default
finetuning_type: lora

# Export
export_dir: /home/bingxing2/home/scx6592/bailong/models/llama3-icews14-stage1-sft
export_size: 2
export_device: cpu
export_legacy_format: false
