### model
model_name_or_path: models/GL-GDELT-WIKI-130k-RID
adapter_name_or_path: outputs/SL-ST-ICEWS18-GID
infer_backend: huggingface

### method
stage: sft
finetuning_type: lora
lora_target: all

### dataset
prepare_dir: processed
dataset: ICEWS18
template: empty
cutoff_len: 1024
preprocessing_num_workers: 8

### Process options
history_strategy: hop
history_length: 50
map_strategy: GID
time: session
entity: true
relation: true
