ICEWS05-15:
  base_time: 2005-01-01
  norm_factor: 1
  time_unit: day
  adjust_time: false
ICEWS14:
  base_time: 2014-01-01
  norm_factor: 1
  time_unit: day
  adjust_time: true
ICEWS18:
  base_time: 2018-01-01
  norm_factor: 24
  time_unit: day
  adjust_time: false
GDELT:
  base_time: 2018-01-01
  norm_factor: 1
  time_unit: 15min
  adjust_time: false
WIKI:
  base_time: 1786-01-01
  norm_factor: 1
  time_unit: year
  adjust_time: false
YAGO:
  base_time: 1830-01-01
  norm_factor: 1
  time_unit: year
  adjust_time: false
