data_dir: D:\Data\tkg_data
datasets:
  ICEWS05-15:
    base_time: 2005-01-01
    time_unit: day
  ICEWS14s:
    base_time: 2014-01-01
    time_unit: day
  ICEWS18:
    base_time: 2018-01-01
    time_unit: hour
  GDELT:
    base_time: 2018-01-01
    time_unit: 15min
  WIKI:
    base_time: 1786
    time_unit: year
  YAGO:
    base_time: 1830
    time_unit: year
