# Dataset setting
dataset_dir: /home/bingxing2/home/scx6592/bailong/data/tkg_data
prepare_dir: /home/bingxing2/home/scx6592/bailong/data/llm4tkg/prepare
train_dataset: ICEWS14
valid_dataset: ICEWS14
test_dataset: ICEWS14
history_type: entity
history_direction: uni
history_length: 30
anonymize_strategy: session
anonymize_prefix: false
time_process_strategy: query
vague_time: false
prompt_construct_strategy: qa
candidate_relabel: false

