CUDA_VISIBLE_DEVICES=0 python -m src.sft.run_tsro \
    --dataset_dir /data/bailong/data/tkg_data \
    --dataset ICEWS14 \
    --prepare_dir /data/bailong/data/tkg_data/prepare \
    --num_predictions 30 \
    --anonymize_entity False \
    --anonymize_rel False \
    --anonymize_time True \
    --model_name_or_path /data/bailong/models/gpt2 \
    --output_dir /data/bailong/data/tkg_data/results \
    --do_predict \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --predict_with_generate True
