CUDA_VISIBLE_DEVICES=0 python -m src.tsro.workflow \
    --dataset_dir /data/bailong/data/tkg_data \
    --dataset ICEWS14 \
    --prepare_dir /data/bailong/data/tkg_data/prepare \
    --model_name_or_path /data/bailong/models/opt-350m \
    --output_dir /data/bailong/data/tkg_data/result \
    --logging_steps 10 \
    --save_steps 500 \
    --plot_loss True \
    --overwrite_output_dir True \
    --do_train \
    --do_eval \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --learning_rate 0.0001 \
    --num_train_epochs 1.0 \
    --lr_scheduler_type cosine \
    --per_device_eval_batch_size 1 \
    --evaluation_strategy steps \
    --eval_steps 500 \
    --do_predict
