# Paths
dataset_dir: /home/gomall/datasets/TKG-forecast
dataset: ICEWS14,ICEWS18,GDELT
prepare_dir: prepare

# Process options
history_strategy: hop
history_length: 50
map_strategy: global
time: session
entity: true
relation: true
max_samples:
