# Model
model_name_or_path: /data/bailong/models/opt-350m
adapter_name_or_path: /data/bailong/data/llm4tkg/saves/opt-350m-icews14-stage1-sft
template: default
finetuning_type: lora

# Export
export_dir: /data/bailong/models/opt-350m-icews14-stage1-sft
export_size: 2
export_device: cpu
export_legacy_format: false
