# Paths
dataset_dir: /home/gomall/datasets/TKG-forecast
dataset: GDELT
prepare_dir: prepare
partition: train

# Process options
history_strategy: hop
history_length: 50
map_strategy: session
time: session
entity: true
relation: true
max_samples: 100000
