# Paths
dataset_dir: /home/gomall/datasets/TKG-forecast
dataset: GDELT
prepare_dir: prepare

# Process options
history_strategy: hop
history_length: 50
map_strategy: session
time: session
entity: false
relation: false
max_samples: 100000
